services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base-image:latest

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file watching in Docker

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Mount Azure CLI configuration for authentication (writable)
      - ~/.azure:/root/.azure
      # Mount Azure CLI cache for token persistence (writable)
      - ~/.azure-cli:/root/.azure-cli
      # Note: Environment variables are read from host system or root .env file
    depends_on:
      - audio
      - sentiment
      - transcriber
    environment:
      - NODE_ENV=development
      # Enable Azure CLI authentication
      - AZURE_CONFIG_DIR=/root/.azure
      # Azure AI Foundry configuration (set these in your .env file)
      - AZURE_AI_FOUNDRY_ENDPOINT=${AZURE_AI_FOUNDRY_ENDPOINT:-}
      - AZURE_AI_FOUNDRY_RESPONSE_CONTENT_ANALYSIS_AGENT_ID=${AZURE_AI_FOUNDRY_RESPONSE_CONTENT_ANALYSIS_AGENT_ID:-}
      - AZURE_AI_FOUNDRY_RESPONSE_SENTIMENT_ANALYSIS_AGENT_ID=${AZURE_AI_FOUNDRY_RESPONSE_SENTIMENT_ANALYSIS_AGENT_ID:-}
      - AZURE_AI_FOUNDRY_JOB_DESCRIPTION_KEYWORDS_GENERATION_AGENT_ID=${AZURE_AI_FOUNDRY_JOB_DESCRIPTION_KEYWORDS_GENERATION_AGENT_ID:-}
      - AZURE_AI_FOUNDRY_KEYWORD_ANALYSIS_AGENT_ID=${AZURE_AI_FOUNDRY_KEYWORD_ANALYSIS_AGENT_ID:-}

  audio:
    build:
      context: ./audio-analysis
      dockerfile: Dockerfile
    image: audio-service
    ports:
      - "8000:8000"
    volumes:
      - ./audio-analysis:/app
    depends_on:
      - base

  sentiment:
    build:
      context: ./sentiment-analysis
      dockerfile: Dockerfile
    image: sentiment-service
    ports:
      - "8001:8001"
    volumes:
      - ./sentiment-analysis:/app
    depends_on:
      - base

  transcriber:
    build:
      context: ./transcriber
      dockerfile: Dockerfile
    image: transcriber-service
    ports:
      - "8002:8002"
    volumes:
      - ./transcriber:/app
    depends_on:
      - base
