services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
     - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - audio
      - sentiment
      - transcriber

  # audio:
  #   build:
  #     context: .
  #     dockerfile: audio-analysis/Dockerfile
  #   ports:
  #     - "8000:8000"

  sentiment:
    build:
      context: .
      dockerfile: sentiment-analysis/Dockerfile
    ports:
      - "8001:8001"

  transcriber:
    build:
      context: .
      dockerfile: transcriber/Dockerfile
    ports:
      - "8002:8002"
